# -*- coding: utf-8 -*-
"""Streamlit-TDS-GA8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x1WfDoJR7-gBFipU7lsXAYzMfc63gDtg
"""

import streamlit as st

def largest_num(a, b, c):
    """
    Returns the largest number among a, b, c
    """
    return max(a, b, c)

def main():
    st.title("Find the largest number")
    st.write("Enter three numbers below:")

    a = st.number_input("Enter the first number:")
    b = st.number_input("Enter the second number:")
    c = st.number_input("Enter the third number:")

    if st.button("Find the largest"):
        result = largest_num(a, b, c)
        st.write(f"The largest number is: {result}")

if __name__ == "__main__":
    main()